### ISSUE TITLE
生成的js代码 少一个结束符 会导致报错

### ISSUE THREAD

**Issue by Julyssn** [laravel-admin-extensions/quill#3]
![image](https://user-images.githubusercontent.com/46492039/102083870-38ba3d00-3e4f-11eb-862a-8dce02b6487a.png)
![image](https://user-images.githubusercontent.com/46492039/102083903-45d72c00-3e4f-11eb-9ba9-159ee7e87bc5.png)
![image](https://user-images.githubusercontent.com/46492039/102083985-60110a00-3e4f-11eb-8750-bc0d8f17a410.png)
请在生成的js代码后面加上 ';' 结尾符号

**Comment by Julyssn** [comment]
或者在最后多换行一次

**Comment by jxlwqq** [comment]
已经发布了，更新下 https://packagist.org/packages/jxlwqq/quill#1.0.2

**Comment by Julyssn** [comment]
更新好了 感谢大佬
